name: Daily Weather Ingestion

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  weather-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests azure-storage-blob python-dotenv

      - name: Run ingestion script
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: python ingestion/Weather_api_ingestion.py
