version: 2

models:
  - name: stg_weather_data
    description: "Staging model for cleaned weather data."

    columns:
      - name: city
        description: "City name"
        tests:
          - not_null

      - name: weather_date
        description: "Date of the weather observation"
        tests:
          - not_null

      - name: temperature_max
        description: "Maximum temperature recorded"

  - name: weather_summary
    description: "Gold mart summarizing weather data by city."

    columns:
      - name: city
        description: "City name"
        tests:
          - unique
          - not_null

      - name: number_of_days
        description: "Number of weather records"

      - name: avg_temperature
        description: "Average maximum temperature"

      - name: highest_temperature
        description: "Highest recorded temperature"